FROM --platform=linux/arm/v7 node:12.2.0 as build-stage

WORKDIR /ui
COPY package*.json ./
RUN npm install
COPY ./ .
RUN npm run build

FROM nginx as production-stage
RUN mkdir /ui
COPY --from=build-stage /edge_interface/dist /ui
COPY nginx.conf /etc/nginx/nginx.conf
