apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: edge-orchestrator
  name: edge-orchestrator
  namespace: vio
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: back
      app.kubernetes.io/instance: vio
      app.kubernetes.io/name: edge-orchestrator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/component: back
        app.kubernetes.io/instance: vio
        app.kubernetes.io/name: edge-orchestrator
    spec:
      containers:
      - env:
        - name: API_CONFIG
          value: edge-gcp
        - name: SERVING_MODEL_URL
          value: https://predictions.vio.octo.tools
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/gcp/sa_credentials.json
        - name: GCP_BUCKET_NAME
          value: tf-vio-bucket
        image: europe-west1-docker.pkg.dev/acn-gcp-octo-sas/tf-vio-artifacts/edge_orchestrator:1.1
        imagePullPolicy: IfNotPresent
        name: edge-orchestrator
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        readinessProbe:
          httpGet:
            port: http
            path: /api/v1/
          initialDelaySeconds: 30
          periodSeconds: 5
        livenessProbe:
          httpGet:
            port: http
            path: /api/v1/
          initialDelaySeconds: 30
          periodSeconds: 5
        volumeMounts:
        - mountPath: /etc/gcp
          mountPropagation: None
          name: service-account-credentials-volume
          readOnly: true
#      imagePullSecrets:
#        - name: github-container-registry
      restartPolicy: Always
      volumes:
      - name: service-account-credentials-volume
        secret:
          defaultMode: 420
          items:
          - key: sa_json
            path: sa_credentials.json
          optional: false
          secretName: service-account-credentials
