apiVersion: v1
kind: Service
metadata:
  labels:
    app: edge-orchestrator
    app.kubernetes.io/component: back
    app.kubernetes.io/instance: vio
    app.kubernetes.io/name: edge-orchestrator
  name: edge-orchestrator
  namespace: vio
spec:
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app.kubernetes.io/component: back
    app.kubernetes.io/instance: vio
    app.kubernetes.io/name: edge-orchestrator
  type: LoadBalancer
