services:
  edge_model_serving:
    extends:
      file: edge_model_serving/edge_model_serving.yml
      service: edge_model_serving

  edge_orchestrator:
    extends:
      file: edge_orchestrator/edge_orchestrator.yml
      service: edge_orchestrator

  edge_interface:
    extends:
      file: edge_interface/edge_interface.yml
      service: edge_interface
