services:
  edge_model_serving:
    extends:
      file: edge/model_serving/tflite_serving/edge_model_serving.yml
      service: edge_model_serving

  edge_orchestrator:
    extends:
      file: edge/orchestrator/edge_orchestrator.yml
      service: edge_orchestrator

  edge_camera:
    extends:
      file: edge/camera/edge_camera.yml
      service: edge_camera

  edge_cockpit:
    extends:
      file: edge/cockpit/edge_cockpit.yml
      service: edge_cockpit
    depends_on:
      - edge_orchestrator

  hub_labelizer:
    extends:
      file: hub/labelizer/hub_labelizer.yml
      service: hub_labelizer

  hub_streamlit:
    extends:
      file: hub/streamlit/hub_streamlit.yml
      service: hub_streamlit
