version: '3'

services:
  edge_db:
    image: mongo:5.0.2
    container_name: edge_db
    ports:
      - 27017:27017

  edge_model_serving:
    container_name: edge_model_serving
    build:
      context: tflite_serving
      dockerfile: Dockerfile
    environment:
      - TF_CPP_MIN_VLOG_LEVEL=0
    ports:
      - 8501:8501
    volumes:
      - ./model_serving:/models

  edge_orchestrator:
    container_name: edge_orchestrator
    build:
      context: supervisor
      dockerfile: Dockerfile
    volumes:
      - ./supervisor/data/storage:/supervisor/data/storage
    ports:
      - 8000:8000

  edge_interface:
    container_name: edge_interface
    build:
      context: edge_interface
      dockerfile: Dockerfile
    ports:
      - 8080:80

  hub_monitoring:
    container_name: hub_monitoring
    image: grafana/grafana:latest
    ports:
      - 4000:3000
    environment:
      - GF_INSTALL_PLUGINS=yesoreyeram-infinity-datasource
    volumes:
      - ./hub_monitoring/dashboards:/var/lib/grafana/dashboards
      - ./hub_monitoring/provisioning:/etc/grafana/provisioning
