services:
  edge_model_serving:
    extends:
      file: edge_model_serving/edge_model_serving.yml
      service: edge_model_serving

  edge_orchestrator:
    extends:
      file: edge_orchestrator/edge_orchestrator.yml
      service: edge_orchestrator

  edge_interface:
    extends:
      file: edge_interface/edge_interface.yml
      service: edge_interface

  hub_streamlit:
    container_name: hub_streamlit
    build:
      context: hub_streamlit
      dockerfile: Dockerfile
    ports:
      - 8500:8500
    environment:
      BUCKET_NAME: tf-vio-bucket
      GOOGLE_APPLICATION_CREDENTIALS: /hub_streamlit/config/secrets/credentials.json
    volumes:
      - ./hub_streamlit/config:/hub_streamlit/config
    profiles: [hub]

  edge_streamlit:
    container_name: edge_streamlit
    build:
      context: edge_streamlit
      dockerfile: Dockerfile
    ports:
      - 8502:8502
    profiles: [edge]
