version: '3'

services:
  edge_db:
    image: mongo:5.0.2
    container_name: edge_db
    ports:
      - 27017:27017

  edge_model_serving:
    container_name: edge_model_serving
    build:
      context: edge_model_serving
      dockerfile: tflite_serving/Dockerfile
    environment:
      - TF_CPP_MIN_VLOG_LEVEL=0
    ports:
      - 8501:8501
    volumes:
      - /home/devkit/Desktop/vio/edge_model_serving/models:/models

  edge_orchestrator:
    container_name: edge_orchestrator
    build:
      context: edge_orchestrator
      dockerfile: Dockerfile
    volumes:
      - /home/devkit/Desktop/vio/edge_orchestrator/data:/edge_orchestrator/data
      - /home/devkit/Desktop/vio/edge_orchestrator/config:/edge_orchestrator/config
    devices:
      - /dev/video0:/dev/video0
#      - /dev/video2:/dev/video2
    ports:
      - 8000:8000
    healthcheck:
      test: [ "CMD-SHELL", "nc -zv 0.0.0.0 5432" ]
      interval: 5s
      timeout: 5s
      retries: 5

  edge_interface:
    container_name: edge_interface
    build:
      context: edge_interface
      dockerfile: Dockerfile
    ports:
      - 8080:80
