site_name: vio
site_url: https://github.com/octo-technology/VIO
repo_url: https://github.com/octo-technology/VIO
theme: readthedocs
nav:
    - Home: index.md
    - Core: supervisor.md
    - Deployment:
        - edge onboarding: edge_deployment.md
        - cloud infra deployment: cloud_deployment.md
    - Model serving: model_serving.md
    - Edge interface: edge_interface.md
    - Monitoring: monitoring.md
    - Contribute:
      - Contribute: CONTRIBUTING.md
      - Organization: ORGANIZATION.md
