site_name: vio
site_url: https://github.com/octo-technology/VIO
repo_url: https://github.com/octo-technology/VIO
theme:
  name: material
nav:
    - Getting Started: index.md
    - Overview: overview.md
    - Edge orchestrator: edge_orchestrator.md
    - Edge model serving: edge_model_serving.md
    - Edge interface: edge_interface.md
    - Edge Deployment: edge_deployment.md
    - Hub monitoring: hub_monitoring.md
    - Hub Deployment: hub_deployment.md
    - Contribute:
      - Contributing: CONTRIBUTING.md
      - Organization: ORGANIZATION.md
      - CI-CD: CICD.md
      - Documentation: DOCUMENTATION.md
      - License: LICENSE.md
      - Authors: AUTHORS.md
