apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: health-check-config
spec:
  healthCheck:
#    checkIntervalSec: INTERVAL
#    timeoutSec: TIMEOUT
#    healthyThreshold: HEALTH_THRESHOLD
#    unhealthyThreshold: UNHEALTHY_THRESHOLD
    type: HTTP
    requestPath: /api/v1
    port: 8000