services:
  edge_orchestrator:
    container_name: edge_orchestrator
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILDOS: ${BUILDOS:-linux}
    volumes:
      - ./data_storage:/edge_orchestrator/data_storage
      - /run/udev:/run/udev:ro  # Corresponds to mounting point of Raspberry Pi camera device
    devices:
      - /dev/video0:/dev/video0  # Corresponds to mounting point of integrated webcam device
      - /dev/video4:/dev/video4  # Corresponds to mounting point of USB camera device
    ports:
      - 8000:8000
    environment:
      SERVING_MODEL_URL: http://edge_model_serving:8501
    privileged: true
    profiles: [edge]
