[build-system]
requires = ["setuptools>=66", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[project]
name = "edge_orchestrator"
dynamic = ["readme"]
version = "0.2.0"
authors = [
    { name = "BAPO", email = "bapo@octo.com" },
    { name = "GIRE", email = "gire@octo.com" },
    { name = "KSA", email = "ksa@octo.com" },
    { name = "ROLO", email = "rolo@octo.com" },
    { name = "THAN", email = "than@octo.com" },
    { name = "YDR", email = "ydr@octo.com" },
]
description = 'vio-edge: orchestrator module'
classifiers = [
    'Programming Language :: Python :: 3',
    'License :: OSI Approved :: Apache2.0',
    'Operating System :: OS Independent',
]
dependencies = [
    "aiohttp==3.8.3",
    "azure-iot-device==2.12.0",
    "codecarbon==2.5.O",
    "fastapi[all]==0.100.0",
    "numpy==1.24.1",
    "Pillow==9.3.0",
    "psycopg2-binary==2.9.5",
    "psycopg2==2.9.3",
    "pymongo==4.3.3",
    "smart_open[azure]==6.3.0",
    "google-cloud-storage==2.2.1",
]
requires-python = ">=3.8.10"


[project.optional-dependencies]
dev = [
    "alembic==1.11.1",
    "autoflake==2.3.1",
    "behave @ git+https://github.com/behave/behave@v1.2.7.dev3#egg=behave[toml]",
    "black==23.7.0",
    "flake8==6.0.0",
    "freezegun==1.2.2",
    "isort==5.13.2",
    "pytest==7.2.1",
    "pytest-asyncio==0.20.3",
    "pytest-cov==4.0.0",
    "python-dotenv==0.21.1",
    "requests[security]==2.28.2",
    "testcontainers==3.7.1"
]
raspberry = [
    "picamera==1.13"
]

[project.scripts]
edge_orchestrator = "edge_orchestrator.__main__:main"

[project.urls]
homepage = "https://github.com/octo-technology/VIO"
documentation = "https://octo-technology.github.io/VIO/"
changelog = "https://github.com/octo-technology/VIO/compare/"

[tool.behave]
junit = true
junit_directory = "reports/behave/"
logging_clear_handlers = true
paths = ["tests/functional_tests"]

[tool.black]
line-length = 120
target-version = ["py38", "py39", "py310", "py311"]
verbose = true

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
min_version = "6.0"
testpaths = "tests/unit_tests"
norecursedirs = [".git", "venv/", ".pytest_cache/", "main/"]

[tool.setuptools.dynamic]
readme = { file = ["README.rst", "USAGE.rst"] }

[tool.setuptools.packages.find]
where = ["edge_orchestrator/"]
exclude = ["tests*", "data"]

[tool.setuptools.package-data]
edge_orchestrator = ["logger.cfg"]
