- name: "Deploy vio on edge and launch"
  hosts: all
  tasks:
    - name: Remove config folder
      ansible.builtin.file:
        path: "{{ REMOTE_VIO_DIR }}/edge_orchestrator/config"
        state: absent

    - name: Copy config on the remote machine
      ansible.builtin.copy:
        src:  "{{ LOCAL_VIO_DIR }}/edge_orchestrator/config"
        dest: "{{ REMOTE_VIO_DIR }}/edge_orchestrator/"

    - name: Remove model folder
      ansible.builtin.file:
        path: "{{ REMOTE_VIO_DIR }}/edge_model_serving/models"
        state: absent

    - name: Copy model file on the remote machine
      ansible.builtin.copy:
        src:  "{{ LOCAL_VIO_DIR }}/edge_model_serving/models/tflite"
        dest: "{{ REMOTE_VIO_DIR }}/edge_model_serving/models/"

    - name: Copy docker compose
      ansible.builtin.template:
        src: "{{ LOCAL_VIO_DIR }}/deployment/edge/ansible/files/docker-compose.template.yml"
        dest: "{{ REMOTE_VIO_DIR }}/docker-compose.yml"
    
    - name: Copy Makefile
      ansible.builtin.template:
        src: "{{ LOCAL_VIO_DIR }}/deployment/edge/ansible/files/Makefile.template"
        dest: "{{ REMOTE_VIO_DIR }}/Makefile"

    - name: Start all edge services on intel (model_serving, orchestrator, interface)
      make:
        chdir: "{{ REMOTE_VIO_DIR }}"
        target: vio-edge-up
