- name: "Deploy vio on edge and launch"
  hosts: all
  tasks:
    - name: Create directory for vio on edge
      ansible.builtin.file:
        path: "{{ REMOTE_VIO_DIR }}"
        state: directory
        mode: '0755'

    - name: Copy Makefile
      ansible.builtin.copy:
        src: "{{ LOCAL_VIO_DIR }}/deployment/edge/ansible/files/Makefile"
        dest: "{{ REMOTE_VIO_DIR }}/Makefile"

    - name: Template docker compose
      ansible.builtin.template:
        src: "{{ LOCAL_VIO_DIR }}/deployment/edge/ansible/files/docker-compose.template.yml"
        dest: "{{ REMOTE_VIO_DIR }}/docker-compose.yml"

    - name: Start all edge services on intel (model_serving, orchestrator, interface)
      make:
        chdir: "{{ REMOTE_VIO_DIR }}"
        target: vio-edge-up
