- name: "Deploy vio on edge and launch"
  hosts: all
  tasks:
    - name: Create edge_ip file
      ansible.builtin.copy:
        content: "{{ IP_ADDRESS }}"
        dest: "{{ REMOTE_VIO_DIR }}/edge_orchestrator/config/edge_ip.txt"

    - name: Upload edge_ip file on GCP
      gcp_compute_file:
        project: "{{ GCP_PROJECT }}"
        auth_kind: "{{ GCP_AUTH_KIND }}"
        service_account_file: "{{ GCP_SERVICE_ACCOUNT_FILE }}"
        instance_name: "{{ GCP_INSTANCE_NAME }}"
        zone: "{{ GCP_ZONE }}"
        remote_src: "{{ REMOTE_VIO_DIR }}/edge_orchestrator/config/edge_ip.txt"
        src: "{{ REMOTE_VIO_DIR }}/edge_orchestrator/config/edge_ip.txt"
