- name: "Register edge on GCP hub"
  hosts: all
  tasks:
    - name: Create edge_ip file
      ansible.builtin.copy:
        content: "{{ IP_ADDRESS }}"
        dest: "{{ REMOTE_VIO_DIR }}/edge_orchestrator/config/edge_ip.txt"

    - name: Install pip through apt
      ansible.builtin.apt:
        name: python3-pip

    - name: Install google-cloud-storage
      ansible.builtin.pip:
        name: google-cloud-storage
        version: 3.0.0

    - name: Upload edge_ip file on GCP
      google.cloud.gcp_storage_object:
        action: upload
        bucket: "{{ GCP_VIO_BUCKET }}"
        dest: "{{ EDGE_NAME }}/edge_ip.txt"
        src: "{{ REMOTE_VIO_DIR }}/edge_orchestrator/config/edge_ip.txt"
        project: "{{ GCP_VIO_PROJECT }}"
        auth_kind: "serviceaccount"
        service_account_file: "{{ REMOTE_VIO_DIR }}/edge_orchestrator/config/secrets/credentials.json"
