- name: "Deploy vio on edge and launch"
  hosts: all
  tasks:
    - name: Create edge_ip file
      ansible.builtin.copy:
        content: "{{ IP_ADDRESS }}"
        dest: "{{ LOCAL_VIO_DIR }}/edge_orchestrator/config/edge_ip.txt"
    - name: Upload edge_ip file on GCP
      google.cloud.gcp_storage_object:
        action: upload
        bucket: "{{ REMOTE_VIO_BUCKET }}"
        dest: "{{ EDGE_NAME }}/edge_ip.txt"
        src: "{{ LOCAL_VIO_DIR }}/edge_orchestrator/config/edge_ip.txt"
        project: acn-gcp-octo-sas
        auth_kind: "serviceaccount"
        service_account_file: "{{ LOCAL_VIO_DIR }}/edge_orchestrator/acn-gcp-octo-sas-d657d0330cec.json"