- name: "Install repo"
  hosts: edge_1
  tasks:
    - ansible.builtin.git:
        repo: https://github.com/octo-technology/VIO.git
        dest: "{{ REMOTE_VIO_DIR }}"
        single_branch: yes
        version: deploy_vio_on_edge
        force: true

    - name: Copy config on the remote machine
      ansible.builtin.copy:
        src:  "{{ LOCAL_VIO_DIR }}/edge_orchestrator/config/secrets/acn-gcp-octo-sas-ee685c40af79.json"
        dest: "{{ REMOTE_VIO_DIR }}/edge_orchestrator/config/secrets"


    - name: Copy model file on the remote machine
      ansible.builtin.copy:
        src:  "{{ LOCAL_VIO_DIR }}/edge_model_serving/models/tflite"
        dest: "{{ REMOTE_VIO_DIR }}/edge_model_serving/models/tflite"

