- name: "Install Minikube"
  hosts: localhost
  tasks:
  - community.general.homebrew:
      name: minikube
      state: present

  - shell: minikube start --driver=docker --extra-config=apiserver.service-node-port-range=32760-32767 --ports=127.0.0.1:32760-32767:32760-32767

  - kubernetes.core.k8s:
      name: vio
      api_version: v1
      kind: Namespace
      state: present

  - kubernetes.core.k8s_info:
     kind: Pod
     namespace: vio
    register: pod_list

  - shell: kubectl config set-context --current --namespace=vio
