- name: "Install repo"
  hosts: edge_1
  tasks:
    - ansible.builtin.git:
        repo: https://github.com/octo-technology/VIO.git
        dest: ~/Desktop/vio
        single_branch: yes
        version: deploy_vio_on_edge
        force: true

    - name: Copy config on the remote machine
      ansible.builtin.copy:
        src:  ~/Desktop/airbus/VIO/deployment/edge/ansible/acn-gcp-octo-sas-ee685c40af79.json
        dest: ~/Desktop/vio/edge_orchestrator/config

    - name: Create model directory
      file:
        path: ~/Desktop/vio/edge_model_serving/models/tflite/screw_control/
        state: directory

    - name: Copy model file on the remote machine
      ansible.builtin.copy:
        src:  ~/Desktop/airbus/VIO/deployment/edge/ansible/screw_control.tflite
        dest: ~/Desktop/vio/edge_model_serving/models/tflite/screw_control/


    - name: Create model directory
      file:
        path: ~/Desktop/vio/edge_model_serving/models/tflite/barcode_control/
        state: directory

    - name: Copy model file on the remote machine
      ansible.builtin.copy:
        src:  ~/Desktop/airbus/VIO/deployment/edge/ansible/barcode_control.tflite
        dest: ~/Desktop/vio/edge_model_serving/models/tflite/barcode_control/

