---
RecipeFormatVersion: '2020-01-25'
ComponentName: vio
ComponentVersion: '0.1.3'
ComponentDescription: 'A component that uses Docker Compose to run images from public Amazon ECR and Docker Hub.'
ComponentPublisher: Amazon
ComponentDependencies:
  aws.greengrass.DockerApplicationManager:
    VersionRequirement: ~2.0.0
  aws.greengrass.TokenExchangeService:
    VersionRequirement: ~2.0.0
Manifests:
  - Platform:
      os: all
    Lifecycle:
        run: docker-compose -f {artifacts:path}/docker-compose.raspberrypi.yml up
    Artifacts:
      - URI: "docker:767397954739.dkr.ecr.eu-west-1.amazonaws.com/edge_orchestrator.raspberrypi:latest"
      - URI: "docker:767397954739.dkr.ecr.eu-west-1.amazonaws.com/edge_tflite_serving.raspberrypi:latest"
      - URI: "docker:767397954739.dkr.ecr.eu-west-1.amazonaws.com/edge_interface.raspberrypi:latest"
      - URI: "s3://bapo-greengrass-poc/docker-compose.raspberrypi.yml"