---

project: vio
deployment_env: demo
azure_subscription_id: 0df9d49b-a078-4c4b-90fd-80dae8300df6

# Resource group
resource_group_name: "{{ project }}-rg-{{ deployment_env }}"

# Storage Account
storage_account_name: "{{ project }}storageaccount{{ deployment_env }}"

# Postgres
postgres_server_name: "{{ project }}-postgres-{{ deployment_env }}"
postgres_database_name: vio
postgres_admin_username: "{{ lookup('env', 'POSTGRES_USERNAME') }}"
postgres_admin_password: "{{ lookup('env', 'POSTGRES_PASSWORD') }}"
postgres_firewall_rules:
  - rule_name: open_bar
    start_ip_address: 0.0.0.0
    end_ip_address: 255.255.255.255
postgres_iothub_schema: iothub

# Function App
function_app_name: "{{ project }}-function-app-{{ deployment_env }}"
function_name: telemetry_saver

# Event Grid
event_grid_system_topic_name: "{{ project }}-system-topic-{{ deployment_env }}"
event_grid_subscription_name: "{{ project }}-system-topic-subscription-{{ deployment_env }}"

# Gitlab container registry
registry_url: registry.gitlab.com
registry_username: "{{ lookup('env', 'REGISTRY_USERNAME') }}"
registry_password: "{{ lookup('env', 'REGISTRY_PASSWORD') }}"

# IoT Hub
iot_hub_name: "{{ project }}-iothub-{{ deployment_env }}"
device_connection_string: "{{ lookup('env', 'CONNECTION_STRING') }}"
devices:

  - name: "vio-device-raspberrypi-1-{{ deployment_env }}"
    modules_template_name: "modules_vio_device_raspberrypi_1_{{ deployment_env }}.json"
    local_storage_name: blob-storage-raspberry-1
    cloud_storage_name: blob-storage-raspberry-1
    modules:
      mongodb:
        image: webhippie/mongodb
        version: latest-arm32v7
        ports: 27017:27017
      model_serving:
        image: ghcr.io/octo-technology/vio/edge_tflite_serving.raspberrypi
        version: latest
        ports: 8501:8501
        privileged: true
      edge_interface:
        image: ghcr.io/octo-technology/vio/edge_interface.raspberrypi
        version: latest
        ports: 8080:80
      supervisor:
        image: ghcr.io/octo-technology/vio/edge_orchestrator.raspberrypi
        version: latest
        ports: 8000:8000
        # device specific to pi-camera
        device: /dev/vchiq
        # volume /opt/vc specific to pi-camera
        volumes:
          - /opt/vc:/opt/vc
          - /home/pi/Desktop/vio_edge/supervisor/data/storage:/supervisor/data/storage
        privileged: true
        envs:
          API_CONFIG: edge-lite
          AZURE_CONTAINER_NAME: blob-storage-raspberry-1
          AZURE_STORAGE_CONNECTION_STRING: DefaultEndpointsProtocol=http;BlobEndpoint=http://blob_storage:11002/localblobrpi1;AccountName=localblobrpi1;AccountKey=zynPekJoW5LpnRomyTn1aA==;
      blob_storage:
        image: mcr.microsoft.com/azure-blob-storage
        version: latest
        ports: 11002:11002
        volumes:
          - /srv/containerdata:/blobroot
        envs:
          LOCAL_STORAGE_ACCOUNT_NAME: localblobrpi1
          LOCAL_STORAGE_ACCOUNT_KEY: zynPekJoW5LpnRomyTn1aA==

  - name: "vio-device-raspberrypi-2-{{ deployment_env }}"
    modules_template_name: "modules_vio_device_raspberrypi_2_{{ deployment_env }}.json"
    local_storage_name: blob-storage-raspberry-2
    cloud_storage_name: blob-storage-raspberry-2
    modules:
      mongodb:
        image: webhippie/mongodb
        version: latest-arm32v7
        ports: 27017:27017
      model_serving:
        image: ghcr.io/octo-technology/vio/edge_tflite_serving.raspberrypi
        version: latest
        ports: 8501:8501
        privileged: true
      edge_interface:
        image: ghcr.io/octo-technology/vio/edge_interface.raspberrypi
        version: latest
        ports: 8080:80
      supervisor:
        image: ghcr.io/octo-technology/vio/edge_orchestrator.raspberrypi
        version: latest
        ports: 8000:8000
        # device specific to pi-camera
        device: /dev/vchiq
        # volume /opt/vc specific to pi-camera
        volumes:
          - /opt/vc:/opt/vc
          - /home/pi/Desktop/vio_edge/supervisor/data/storage:/supervisor/data/storage
        envs:
          API_CONFIG: edge-lite
          AZURE_CONTAINER_NAME: blob-storage-raspberry-2
          AZURE_STORAGE_CONNECTION_STRING: DefaultEndpointsProtocol=http;BlobEndpoint=http://blob_storage:11002/localblobrpi2;AccountName=localblobrpi2;AccountKey=fMkmWvOzHiawjg1MkEZN3Q==;
        privileged: true
      blob_storage:
        image: mcr.microsoft.com/azure-blob-storage
        version: latest
        ports: 11002:11002
        volumes:
          - /srv/containerdata:/blobroot
        envs:
          LOCAL_STORAGE_ACCOUNT_NAME: localblobrpi2
          LOCAL_STORAGE_ACCOUNT_KEY: fMkmWvOzHiawjg1MkEZN3Q==

# Grafana server
virtual_network_name: "{{ project }}-grafana-virtual-network-{{ deployment_env }}"
subnet_name: "{{ project }}-grafana-subnet-{{ deployment_env }}"
public_ip_name: "{{ project }}-grafana-public-ip-{{ deployment_env }}"
network_security_group_name: "{{ project }}-grafana-network-security-group-{{ deployment_env }}"
network_interface_card_name: "{{ project }}-grafana-network-interface-card-{{ deployment_env }}"
vm_name: grafana
vm_admin_username: grafvio
ssh_public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDSlEdG6CsL2fNoK5+Wqq5DPtJTAc+CUdQvsaijKBCsJu0vRFvF/PqoNo34aD8ujkfvWAr+QnwCRArNsfJVVQcj18xtYcsk7HKwLw73t4mBUaUjeRCkRW8tExNvdCjvEwWjErLwRGBXKnroFA0r60WMbvcowbBdGHIqZ4+dq64T9qYPhvNHlnG484RkpEpDh8T9zEZ/IZARYZ4LRxlNlHqq60C8wmKn0/47tNLyo+BIXd3Ku743ch3u3hoYkHr0S+zVme/VhmBxD8DkrJPEsKROZiRK9hILDwSwfCzweHpDYaFcq+LIZlLarPyoEkeTa8WbQDLBMvo4PRdyBqUFEI8ZuYD+D3M6bYBnUdTj16zUyL1KxtRo2n3eCXrnjp9Vn6qM6po09HHnsrXsIbMbsRaBtvoABz6XSZmzUcewrGD/DGEw9AbnBza4iXWwKKZBjxXprUOzHTyp5HRaEZ0TtXmO+aocAOAtgVGw4ap4zea5DC2JcMdhNxquyOfpYJ0qU/AgWe4/rPqTKPURirOVKnwFlkiOMM8by4j92yAMP62KEz+GGOwT9NKnFF8cqj412IIYils3qSGMxA8qBhimiJXW/BDtMtq6TWcUpYtgzMjvXaW/kD/GGRnamimFdShBvrHybkpT8wDxYLPwjlvnQiqXGV6CXHHBLe3NPJM+iDoA5w== baptiste.ojeanson@AMAC02XH5C9JG5M
ssh_port: 22000
