apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  name: vio-demo
  namespace: vio
spec:
  defaultBackend:
    service:
      name: edge-interface
      port:
        number: 80
  rules:
  - host: vio.octo.tools
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: edge-interface
              port:
                number: 80
        - path: /api
          pathType: Prefix
          backend:
            service:
              name: edge-orchestrator
              port:
                number: 8000
