---

- name: Create virtual network
  azure_rm_virtualnetwork:
    resource_group: "{{ resource_group_name }}"
    name: "{{ virtual_network_name }}"
    address_prefixes: "10.0.0.0/16"

- name: Add subnet
  azure_rm_subnet:
    resource_group: "{{ resource_group_name }}"
    name: "{{ subnet_name }}"
    address_prefix: "10.0.1.0/24"
    virtual_network: "{{ virtual_network_name }}"

- name: Create public IP address
  azure_rm_publicipaddress:
    resource_group: "{{ resource_group_name }}"
    allocation_method: Static
    name: "{{ public_ip_name }}"
  register: output_ip_address

- name: Dump public IP for VM which will be created
  debug:
    msg: "The public IP is {{ output_ip_address.state.ip_address }}."

- name: Create Network Security Group that allows SSH and Grafana port
  azure_rm_securitygroup:
    resource_group: "{{ resource_group_name }}"
    name: "{{ network_security_group_name }}"
    rules:
      - name: SSH 22
        protocol: Tcp
        destination_port_range: 22
        access: Allow
        priority: 1001
        direction: Inbound
      - name: SSH 22000
        protocol: Tcp
        destination_port_range: 22000
        access: Allow
        priority: 1002
        direction: Inbound
      - name: Grafana
        protocol: Tcp
        destination_port_range: 3000
        access: Allow
        priority: 1003
        direction: Inbound

- name: Create virtual network interface card
  azure_rm_networkinterface:
    resource_group: "{{ resource_group_name }}"
    name: "{{ network_interface_card_name }}"
    virtual_network: "{{ virtual_network_name }}"
    subnet: "{{ subnet_name }}"
    public_ip_name: "{{ public_ip_name }}"
    security_group: "{{ network_security_group_name }}"

- name: Create VM
  azure_rm_virtualmachine:
    resource_group: "{{ resource_group_name }}"
    name: "{{ vm_name }}"
    vm_size: Standard_DS1_v2
    admin_username: "{{ vm_admin_username }}"
    ssh_password_enabled: false
    ssh_public_keys:
      - path: "/home/{{ vm_admin_username }}/.ssh/authorized_keys"
        key_data: "{{ ssh_public_key }}"
    network_interfaces: "{{ network_interface_card_name }}"
    image:
      offer: UbuntuServer
      publisher: Canonical
      sku: "18.04-LTS"
      version: latest
