---

- name: Add Microsoft package referential
  become: true
  get_url:
    url: https://packages.microsoft.com/config/debian/stretch/multiarch/prod.list
    dest: /etc/apt/sources.list.d/microsoft-prod.list

- name: Add Microsoft GPG key
  become: true
  shell: curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > /etc/apt/trusted.gpg.d/microsoft.gpg

- name: Update apt-get
  become: true
  apt:
    update_cache: yes

- name: Install moby-engine
  become: true
  apt:
    name: moby-engine
    state: present

- name: Install IoT Edge
  become: true
  apt:
    name: aziot-edge
    state: present
