services:
  edge_model_serving:
    container_name: edge_model_serving
    image: ghcr.io/octo-technology/vio/edge_tflite_serving:latest
    environment:
      TF_CPP_MIN_VLOG_LEVEL: 0   # TensorFlow logging level
    ports:
      - 8501:8501
    volumes:
      - ./edge_model_serving/models:/models

  edge_orchestrator:
    container_name: edge_orchestrator
    image: ghcr.io/octo-technology/vio/edge_orchestrator:latest
    volumes:
      - ./data_storage:/edge_orchestrator/data_storage
      - /run/udev:/run/udev:ro  # udev is the device manager for the Linux kernel, responsible for managing device nodes in the /dev directory dynamically
    ports:
      - 8000:8000
    environment:
      EDGE_NAME: "{{ EDGE_NAME }}"
      SERVING_MODEL_URL: http://edge_model_serving:8501
      GOOGLE_APPLICATION_CREDENTIALS: /edge_orchestrator/config/secrets/credentials.json
      BUCKET_NAME: tf-vio-bucket
      ACTIVE_CONFIG_NAME: marker_classification_with_1_fake_camera
    privileged: true

  edge_interface:
    container_name: edge_interface
    image: ghcr.io/octo-technology/vio/edge_interface:latest
    ports:
      - 8080:80

  edge_streamlit:
    container_name: edge_streamlit
    image: ghcr.io/octo-technology/vio/edge_streamlit:latest
    ports:
      - 8502:8502
