services:
  edge_model_serving:
    container_name: edge_model_serving
    build:
      context: edge_model_serving
      dockerfile: tflite_serving/Dockerfile
      args:
        BUILDOS: ${BUILDOS:-linux}
    environment:
      TF_CPP_MIN_VLOG_LEVEL: 0   # TensorFlow logging level
    ports:
      - 8501:8501
    volumes:
      - ./edge_model_serving/models:/models

  edge_orchestrator:
    container_name: edge_orchestrator
    build:
      context: edge_orchestrator
      dockerfile: Dockerfile
      args:
        BUILDOS: ${BUILDOS:-linux}
    volumes:
      - ./data_storage:/edge_orchestrator/data_storage
    devices:
      - /dev/video0:/dev/video0
      - /dev/video2:/dev/video2
    ports:
      - 8000:8000
    environment:
      EDGE_NAME: "{{ EDGE_NAME }}"
      API_CONFIG: upload-gcp
      SERVING_MODEL_URL: http://edge_model_serving:8501
      GOOGLE_APPLICATION_CREDENTIALS: /edge_orchestrator/config/secrets/credentials.json
      BUCKET_NAME: tf-vio-bucket
      ACTIVE_CONFIG_NAME: marker_classification_with_1_fake_camera

  edge_interface:
    container_name: edge_interface
    build:
      context: edge_interface
      dockerfile: Dockerfile
    ports:
      - 8080:80

  edge_streamlit:
    container_name: edge_streamlit
    build:
      context: edge_streamlit
      dockerfile: Dockerfile
    ports:
      - 8502:8501
