- name: "Set up the device environment for AWS IoT Greengrass Core software"
  hosts: all
  roles:
    - role: check_env_vars
      vars:
        - env_vars: [SSH_PUB_KEY_PATH, AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_SESSION_TOKEN]
    - role: setup_device_in_passwordless_mode_with_ssh
    - role: install_required_tools
    - role: create_user_for_aws_iot_greengrass
      become: true
    - role: download_aws_iot_greengrass_core_software
      remote_user: root
    - role: install_aws_iot_greengrass_core_software
