---

- name: Install and configure Azure IoT Edge agent on Raspberry PI
  hosts: localhost
  connection: local
  roles:
    - role: check_env_vars
      vars:
        - env_vars: [CONNECTION_STRING]
    - role: install_iot_edge_dependencies
    - role: configure_iot_edge
