.base_job_supervisor:
  image: python:3.9
  before_script:
    - cd supervisor
    - pip install .[dev]
  only:
    refs:
      - master
      - merge_requests


pep8:
  stage: Lint
  extends: .base_job_supervisor
  script:
    - flake8

supervisor_tests:
  stage: Test
  extends: .base_job_supervisor
  services:
    - name: mongo:5.0.2
      alias: mongo
    - name: registry.gitlab.com/octo-technology/les-bg-de-la-data/s-s-all/tribu/tribu-augi/asset/vio_edge/model_serving:latest
      alias: model_serving
    - name: registry.gitlab.com/octo-technology/les-bg-de-la-data/s-s-all/tribu/tribu-augi/asset/vio_edge/tflite_serving:latest
      alias: tflite_serving
  script:
    - export DATABASE_CONNECTION_URL='mongodb://mongo:27017'
    - export TENSORFLOW_SERVING_HOST='model_serving'
    - export TENSORFLOW_SERVING_PORT='8501'
    - export TFLITE_SERVING_HOST='tflite_serving'
    - export TFLITE_SERVING_PORT='8501'
    - make tests

tests_pyramid:
  stage: Test
  extends: .base_job_supervisor
  script:
    - pip install anybadge
    - make pyramid_and_badges
  artifacts:
    paths:
      - $CI_PROJECT_DIR/supervisor/badges/badge_func_tests.svg
      - $CI_PROJECT_DIR/supervisor/badges/badge_int_tests.svg
      - $CI_PROJECT_DIR/supervisor/badges/badge_unit_tests.svg
    when: always
    expire_in: 1 day

build_and_push_supervisor_to_registry:
  extends: .build_image_and_push_to_registry
  variables:
    SERVICE_NAME: supervisor
    IMAGE_NAME: supervisor
  only:
    - master

build_and_push_supervisor_raspberrypi_to_registry:
  extends: .build_raspberrypi_image_and_push_to_registry
  variables:
    SERVICE_NAME: supervisor
    IMAGE_NAME: supervisor_raspberrypi
