---

- name: Create VIO IoT Hub
  azure.azcollection.azure_rm_iothub:
    name: "{{ iot_hub_name }}"
    resource_group: "{{ resource_group_name }}"

- name: Get information of the 'iothubowner' policy
  shell: az iot hub policy show --name iothubowner --hub-name {{ iot_hub_name }}
  register: policyInfo

- name: Extract the primary key for the 'iothubowner'
  set_fact:
    primaryKey: "{{ policyInfo.stdout | from_json | json_query('primaryKey') }}"

- name: Create IoT Edge device identities
  azure.azcollection.azure_rm_iotdevice:
    hub: "{{ iot_hub_name }}"
    name: "{{ item.name }}"
    hub_policy_name: iothubowner
    hub_policy_key: "{{ primaryKey }}"
    edge_enabled: yes
  loop: "{{ devices }}"

- name: Get connection string of storage account
  shell: az storage account show-connection-string --name {{ storage_account_name }} --resource-group {{ resource_group_name }}
  register: connection_string_json

- name: Extract the connection string value from the json
  set_fact:
    storage_account_connection_string: "{{ connection_string_json.stdout | from_json | json_query('connectionString') }}"

- name: Prepare modules template for each device
  template:
    src: "modules.json.j2"
    dest: "{{ deployment_files_folder }}/{{ item.modules_template_name }}"
  loop: "{{ devices }}"

- name: Set modules (Docker images) for each IoT Edge device
  # For more information about the json file: https://docs.microsoft.com/en-us/azure/iot-edge/how-to-use-create-options?view=iotedge-2020-11
  shell: |
    az iot edge set-modules --device-id {{ item.name }} \
                            --hub-name {{ iot_hub_name }} \
                            --content {{ deployment_files_folder }}/{{ item.modules_template_name }}
  loop: "{{ devices }}"
