FROM --platform=linux/arm/v7 emacski/tensorflow-serving

WORKDIR /models

COPY tf_serving/models.config /models/models.config
COPY models/tf/inception /models/tf/inception
COPY models/tf/mobilenet_v1_640x640 /models/tf/mobilenet_v1_640x640
COPY models/tf/mask_classification_model /models/tf/mask_classification_model
COPY models/tf/mask_classification_model /models/tf/mask_classification_model
COPY models/tf/marker_quality_control /models/tf/marker_quality_control

ENTRYPOINT ["tensorflow_model_server", "--port=8500", "--rest_api_port=8501", "--model_config_file=/models/models.config"]
