FROM --platform=linux/arm/v7 emacski/tensorflow-serving

WORKDIR /models
COPY ./inception /models/inception
COPY ./mobilenet_v1_640x640 /models/mobilenet_v1_640x640
COPY ./mask_classification_model /models/mask_classification_model
COPY ./marker_quality_control /models/marker_quality_control
COPY ./models.config /models/models.config

ENTRYPOINT ["tensorflow_model_server", "--port=8500", "--rest_api_port=8501", "--model_config_file=/models/models.config"]