---
- name: Create pod for edge-interface
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        labels:
          app: "{{ app }}"
        name: "{{ app }}"
        namespace: "{{ namespace }}"
      spec:
        progressDeadlineSeconds: 600
        replicas: 2
        revisionHistoryLimit: 10
        selector:
          matchLabels:
            app.kubernetes.io/instance: "{{ namespace }}"
            app.kubernetes.io/name: "{{ namespace }}"
            app.kubernetes.io/component: front
        strategy:
          rollingUpdate:
            maxSurge: 25%
            maxUnavailable: 25%
          type: RollingUpdate
        template:
          metadata:
            labels:
              app.kubernetes.io/instance: "{{ namespace }}"
              app.kubernetes.io/name: "{{ namespace }}"
              app.kubernetes.io/component: front
          spec:
            containers:
            - name: "{{ app }}" #pass region, project-id and artifact registery name as var
              image: europe-west1-docker.pkg.dev/acn-gcp-octo-sas/tf-airbus-vio-artifacts/edge_interface:0.5.1
              imagePullPolicy: IfNotPresent
              ports:
                - containerPort: 80
                  name: http
                  protocol: TCP
              readinessProbe:
                httpGet:
                  port: http
                  path: /
                initialDelaySeconds: 30
                periodSeconds: 5
              livenessProbe:
                httpGet:
                  port: http
                  path: /
                initialDelaySeconds: 30
                periodSeconds: 5
            restartPolicy: Always
