name: CI edge_interface
run-name: edge_interface CI on branch >> ${{ github.ref_name }} <<

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'edge_interface/**'


jobs:
  lint_and_test_on_edge_interface:
    name: Run Vue linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 12

      - name: Install dependencies
        run: npm install
        working-directory: ./edge_interface

      - name: Lint
        run: npm run lint
        working-directory: ./edge_interface

  build_and_push_images:
    needs: lint_and_test_on_edge_interface
    strategy:
      fail-fast: false
      matrix:
        include:
          - context: ./edge_interface
            dockerfile: ./edge_interface/Dockerfile
            image: ghcr.io/${{ github.repository }}/edge_interface
    uses: ./.github/workflows/template_build_and_push_docker_images.yml
    with:
      context: ${{ matrix.context }}
      dockerfile: ${{ matrix.dockerfile }}
      image: ${{ matrix.image }}
    secrets:
      username: ${{ github.actor }}
      password: ${{ secrets.GITHUB_TOKEN }}
