name: CI edge-model-server
run-name: edge-model-server CI on branch >> ${{ github.ref_name }} <<

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "edge/model_serving/**"

jobs:
  lint_and_test_on_edge_model_serving:
    name: Run Python linter and tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"

      - name: Install dependencies
        run: make install
        working-directory: ./edge/model_serving/tflite_serving

      - name: Lint with ruff
        run: make check
        working-directory: ./edge/model_serving/tflite_serving

      - name: Run unit tests
        run: make tflite_tests
        working-directory: ./edge/model_serving/tflite_serving

      - name: Upload unit test report
        uses: dorny/test-reporter@v1
        if: ${{ always() }}
        with:
          name: Unit tests report in Python ${{ matrix.python-version }}
          path: edge/model_serving/tflite_serving/reports/tests-report.xml
          reporter: java-junit

  build_and_push_images:
    needs: lint_and_test_on_edge_model_serving
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./edge/model_serving/tflite_serving/Dockerfile
            image: ghcr.io/${{ github.repository }}/edge_tflite_serving
            context: ./edge/model_serving
    uses: ./.github/workflows/template_build_and_push_docker_images.yml
    with:
      context: ${{ matrix.context }}
      dockerfile: ${{ matrix.dockerfile }}
      image: ${{ matrix.image }}
    secrets:
      username: ${{ github.actor }}
      password: ${{ secrets.GITHUB_TOKEN }}
