name: Deploy VIO to GKE
run-name: Deploy VIO to GKE

on:
  workflow_run:
    workflows: ["build_and_push_images"]
    types:
      - completed
  workflow_dispatch:
    inputs:
      new_tag:
        required: true

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT_ID }}
  GKE_CLUSTER: tf-airbus-vio-gke
  GKE_ZONE: europe-west1-b
  GITHUB_REPO: octo-technology/vio
  NAMESPACE: airbus-vio

jobs:
  deploy_on_cluster_gke:
    name: Deploy new images on GKE cluster
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - deployment_name: edge-interface
            image: ghcr.io/${{ env.GITHUB_REPO }}/edge_interface
            new_tag: ${{ inputs.new_tag }}
#          - deployment_name: edge-orchestrator
#            image: ghcr.io/${{ env.GITHUB_REPO }}/edge_orchestrator
#            new_tag: 0.1.0
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Authentication via credentials json
      - name: 'Authentication'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          version: '>= 363.0.0'

      # Get the GKE credentials so we can deploy to the cluster
      - name: 'Set up GKE credentials'
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}

      # Set up kustomize
      - name: 'Set up Kustomize'
        run: |-
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x ./kustomize

      # Set up kustomize
      - name: 'Set up Kubectl'
        run: |-
          curl -sfLO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
          kubectl config set-context --current --namespace=${{ env.NAMESPACE }}

      # Deploy the Docker image to the GKE cluster
      - name: 'Deploy'
        run: |-
          ./kustomize edit set image ${{ matrix.image }}:${{ matrix.new_tag }}
          ./kustomize build . | kubectl apply -f -
          kubectl rollout status deployment/${{ matrix.deployment_name }}
          kubectl get services -o wide
