name: docs generation

on:
  push:
    branches:
      - main

jobs:
  generate_and_deploy_documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install mkdocs
        run: pip install mkdocs-material

      - name: Generate and deploy documentation to Github
        run: mkdocs gh-deploy
