name: Publication vio images for raspberry to Github registry
run-name: Publication vio images for raspberry to Github registry on branch >> ${{ github.ref_name }} <<

on:
  release:
    types:
      - created
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  build_and_push_images:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./edge_interface/Dockerfile.raspberrypi
            image: ghcr.io/${{ github.repository }}/edge_interface.raspberrypi
            context: ./edge_interface
          - dockerfile: ./edge_orchestrator/Dockerfile.raspberrypi
            image: ghcr.io/${{ github.repository }}/edge_orchestrator.raspberrypi
            context: ./edge_orchestrator
          - dockerfile: ./model_serving/Dockerfile.raspberrypi
            image: ghcr.io/${{ github.repository }}/edge_model_serving.raspberrypi
            context: ./model_serving
          - dockerfile: ./tflite_serving/Dockerfile.raspberrypi
            image: ghcr.io/${{ github.repository }}/edge_tflite_serving.raspberrypi
            context: ./tflite_serving
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ matrix.image }}
          tags: type=semver,pattern={{major}}.{{minor}}.{{patch}}
          flavor: latest=auto

      - name: Set up Docker Buildx (multi-platform build)
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker images
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
