---

- hosts: localhost
  tasks:
    - name: Deleting resource group - "{{ resource_group_name }}"
      azure_rm_resourcegroup:
        name: "{{ resource_group_name }}"
        state: absent
        force_delete_nonempty: true
      register: rg
    - debug:
        var: rg
